version: "3.9"
name: hysped
services:
  dev:
    hostname: ${HOSTNAME:-localhost}
    ipc: host
    build:
      context: .
      args:
        NVFLARE_BRANCH: "${NVFLARE_BRANCH:-main}"
      dockerfile: Dockerfile.nvflare-hysped-dev
    image: iisas/nvflare-hysped-dev:latest
    ulimits:
      memlock: -1
      stack: 67108864
    environment:
      - TF_FORCE_GPU_ALLOW_GROWTH=${TF_FORCE_GPU_ALLOW_GROWTH}
      - TF_GPU_MEMORY_LIMIT=${TF_GPU_MEMORY_LIMIT}
      - TF_GPU_ALLOCATOR=cuda_malloc_async
    ports:
      - "8990:8888"
      - "8991:6006"
    volumes:
      - dev_tf:/tf
      - ${PWD}/volumes/dev/root/.netrc:/root/.netrc
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  dev_tf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/volumes/dev/tf

