class Constants():
    GLOBAL_MODEL_NAME = 'global'
    JOB_NAME = 'JOB_NAME'
    JOB_START_TIMESTAMP = 'JOB_START_TIMESTAMP'
    TF_FORCE_GPU_ALLOW_GROWTH = 'TF_FORCE_GPU_ALLOW_GROWTH'
    TF_GPU_MEMORY_LIMIT ='TF_GPU_MEMORY_LIMIT'
    WANDB_ID = 'WANDB_ID'